import React, { useCallback, useEffect, useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import AppButton from "../../components/AppButton"; import AppCard from "../../components/AppCard"; import AppInput from "../../components/AppInput"; import ScreenContainer from "../../components/ScreenContainer"; import InfoBanner from "../../components/ui/InfoBanner"; import LoadingState from "../../components/ui/LoadingState"; import ScreenHeader from "../../components/ui/ScreenHeader"; import StatusBadge from "../../components/ui/StatusBadge";
import { activateAdminUser, deactivateAdminUser, getAdminDrivers } from "../../services/adminService"; import { adminStyles, formatDate } from "./adminUi";
export default function AdminUsersScreen() {
  const [search,setSearch]=useState(""); const [drivers,setDrivers]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [working,setWorking]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const data=await getAdminDrivers({search:search||undefined});setDrivers(data.drivers||[]);}catch(e){setError(e.message);}finally{setLoading(false);}},[search]); useEffect(()=>{load();},[load]);
  async function toggle(driver){setWorking(driver._id);try{driver.isActive?await deactivateAdminUser(driver._id,"Administrative account action"):await activateAdminUser(driver._id);await load();}catch(e){setError(e.message);}finally{setWorking("");}}
  return <ScreenContainer><ScreenHeader eyebrow="Administration" title="Driver Accounts" subtitle="Disable or restore access without deleting user data."/><AppCard><AppInput label="Search drivers" value={search} onChangeText={setSearch}/></AppCard>{error?<InfoBanner tone="danger" message={error}/>:null}{loading?<LoadingState message="Loading users..."/>:null}{drivers.map(driver=><AppCard key={driver._id}><View style={styles.heading}><Text style={styles.title}>{driver.name}</Text><StatusBadge label={driver.isActive?"Active":"Inactive"} tone={driver.isActive?"success":"danger"}/></View><Text style={styles.body}>{driver.email} · {driver.phone}</Text><Text style={styles.body}>Requests: {driver.totalRequests} · Joined: {formatDate(driver.createdAt)}</Text><AppButton title={driver.isActive?"Deactivate":"Activate"} compact variant={driver.isActive?"danger":"success"} loading={working===driver._id} onPress={()=>toggle(driver)}/></AppCard>)}</ScreenContainer>;
}
const styles=StyleSheet.create({...adminStyles,heading:{flexDirection:"row",justifyContent:"space-between",gap:8}});
